-- Refresh existing course URLs to stable learning resources or durable search fallbacks.

BEGIN;

UPDATE courses SET url = 'https://ocw.mit.edu/search/?q=python%20programming' WHERE title ILIKE '%python for software engineers%';
UPDATE courses SET url = 'https://www.coursera.org/search?query=advanced%20python' WHERE title ILIKE '%modern python%';
UPDATE courses SET url = 'https://www.typescriptlang.org/docs/' WHERE title ILIKE '%typescript%';
UPDATE courses SET url = 'https://go.dev/learn/' WHERE title ILIKE '%go:%';
UPDATE courses SET url = 'https://www.google.com/search?q=site:online.stanford.edu+rust+systems+programming' WHERE title ILIKE '%rust%';
UPDATE courses SET url = 'https://www.coursera.org/search?query=data%20structures%20algorithms%20python' WHERE title ILIKE '%data structures%';
UPDATE courses SET url = 'https://fastapi.tiangolo.com/tutorial/' WHERE title ILIKE '%fastapi%';
UPDATE courses SET url = 'https://www.coursera.org/search?query=node.js%20typescript%20backend' WHERE title ILIKE '%node.js%';
UPDATE courses SET url = 'https://grpc.io/docs/languages/go/quickstart/' WHERE title ILIKE '%grpc%';
UPDATE courses SET url = 'https://developer.mozilla.org/en-US/docs/Web/API/WebSockets_API' WHERE title ILIKE '%websocket%';
UPDATE courses SET url = 'https://oauth.net/2/' WHERE title ILIKE '%oauth2%';
UPDATE courses SET url = 'https://www.apollographql.com/tutorials/' WHERE title ILIKE '%graphql%';
UPDATE courses SET url = 'https://www.coursera.org/search?query=api%20gateway%20rate%20limiting' WHERE title ILIKE '%api gateway%';
UPDATE courses SET url = 'https://www.coursera.org/search?query=celery%20redis%20background%20jobs' WHERE title ILIKE '%background workers%';
UPDATE courses SET url = 'https://www.coursera.org/search?query=microservices%20resilience%20circuit%20breaker' WHERE title ILIKE '%circuit breakers%';
UPDATE courses SET url = 'https://www.postgresql.org/docs/current/performance-tips.html' WHERE title ILIKE '%postgresql query%';
UPDATE courses SET url = 'https://supabase.com/docs/guides/database' WHERE title ILIKE '%supabase%';
UPDATE courses SET url = 'https://redis.io/learn/' WHERE title ILIKE '%redis%';
UPDATE courses SET url = 'https://www.pinecone.io/learn/vector-database/' WHERE title ILIKE '%vector databases%';
UPDATE courses SET url = 'https://www.coursera.org/search?query=database%20sharding%20replication' WHERE title ILIKE '%sharding%';
UPDATE courses SET url = 'https://clickhouse.com/learn' WHERE title ILIKE '%time-series%';
UPDATE courses SET url = 'https://www.prisma.io/dataguide' WHERE title ILIKE '%migrations%';
UPDATE courses SET url = 'https://www.google.com/search?q=site:pll.harvard.edu+database+transactions+isolation' WHERE title ILIKE '%acid transactions%';
UPDATE courses SET url = 'https://www.elastic.co/guide/index.html' WHERE title ILIKE '%elastic%';
UPDATE courses SET url = 'https://www.elastic.co/guide/index.html' WHERE title ILIKE '%elasticsearch%';
UPDATE courses SET url = 'https://www.coursera.org/specializations/machine-learning-introduction' WHERE title ILIKE '%machine learning foundations%';
UPDATE courses SET url = 'https://course.fast.ai/' WHERE title ILIKE '%deep learning specialization%';
UPDATE courses SET url = 'https://huggingface.co/learn/nlp-course' WHERE title ILIKE '%transformer%';
UPDATE courses SET url = 'https://www.coursera.org/learn/generative-ai-with-llms' WHERE title ILIKE '%generative ai%';
UPDATE courses SET url = 'https://docs.llamaindex.ai/en/stable/' WHERE title ILIKE '%rag systems%';
UPDATE courses SET url = 'https://www.deeplearning.ai/short-courses/' WHERE title ILIKE '%ai agents%';
UPDATE courses SET url = 'https://huggingface.co/learn' WHERE title ILIKE '%fine-tuning%';
UPDATE courses SET url = 'https://platform.openai.com/docs/guides/prompt-engineering' WHERE title ILIKE '%prompt engineering%';
UPDATE courses SET url = 'https://huggingface.co/tasks' WHERE title ILIKE '%sentence transformers%';
UPDATE courses SET url = 'https://fullstackdeeplearning.com/course/' WHERE title ILIKE '%llmops%';
UPDATE courses SET url = 'https://www.nvidia.com/en-us/training/' WHERE title ILIKE '%guardrails%';
UPDATE courses SET url = 'https://online.stanford.edu/courses' WHERE url ILIKE '%online.stanford.edu%';
UPDATE courses SET url = 'https://graphacademy.neo4j.com/' WHERE title ILIKE '%knowledge graphs%';
UPDATE courses SET url = 'https://github.com/features/copilot' WHERE title ILIKE '%ai code generation%';
UPDATE courses SET url = 'https://react.dev/learn' WHERE title ILIKE '%react%';
UPDATE courses SET url = 'https://tailwindcss.com/docs/installation' WHERE title ILIKE '%tailwind%';
UPDATE courses SET url = 'https://tkdodo.eu/blog/practical-react-query' WHERE title ILIKE '%tanstack%';
UPDATE courses SET url = 'https://observablehq.com/learn' WHERE title ILIKE '%visualizations%';
UPDATE courses SET url = 'https://web.dev/learn/performance' WHERE title ILIKE '%performance%';
UPDATE courses SET url = 'https://ai-sdk.dev/docs' WHERE title ILIKE '%chat uis%';
UPDATE courses SET url = 'https://turborepo.com/docs' WHERE title ILIKE '%turborepo%';
UPDATE courses SET url = 'https://docs.docker.com/get-started/' WHERE title ILIKE '%docker%';
UPDATE courses SET url = 'https://kubernetes.io/docs/tutorials/kubernetes-basics/' WHERE title ILIKE '%kubernetes%';
UPDATE courses SET url = 'https://aws.amazon.com/training/learn-about/architect/' WHERE title ILIKE '%aws cloud%';
UPDATE courses SET url = 'https://docs.github.com/en/actions' WHERE title ILIKE '%github actions%';
UPDATE courses SET url = 'https://developer.hashicorp.com/terraform/tutorials' WHERE title ILIKE '%terraform%';
UPDATE courses SET url = 'https://opentelemetry.io/docs/' WHERE title ILIKE '%opentelemetry%';
UPDATE courses SET url = 'https://www.coursera.org/search?query=cloud%20security%20iam' WHERE title ILIKE '%zero-trust%';
UPDATE courses SET url = 'https://aws.amazon.com/training/learn-about/serverless/' WHERE title ILIKE '%serverless%';
UPDATE courses SET url = 'https://argo-cd.readthedocs.io/en/stable/getting_started/' WHERE title ILIKE '%gitops%';
UPDATE courses SET url = 'https://bytebytego.com/' WHERE title ILIKE '%system design%';
UPDATE courses SET url = 'https://developer.confluent.io/courses/apache-kafka/events/' WHERE title ILIKE '%kafka%';
UPDATE courses SET url = 'https://pdos.csail.mit.edu/6.824/' WHERE title ILIKE '%raft%';
UPDATE courses SET url = 'https://www.coursera.org/search?query=distributed%20systems%20caching%20sharding' WHERE title ILIKE '%caching%';
UPDATE courses SET url = 'https://dataintensive.net/' WHERE title ILIKE '%data-intensive%';
UPDATE courses SET url = 'https://stanford-cs329s.github.io/' WHERE title ILIKE '%vector search%';

COMMIT;
