import { Pool, PoolConfig } from 'pg';
import dotenv from 'dotenv';

dotenv.config();

const connectionString = process.env.SUPABASE_DATABASE_URL;

if (!connectionString) {
  console.warn('⚠️ [DB Warning] SUPABASE_DATABASE_URL is not set in environment variables.');
}

const poolConfig: PoolConfig = {
  connectionString,
  ssl: connectionString?.includes('supabase.co') || process.env.NODE_ENV === 'production'
    ? { rejectUnauthorized: false }
    : undefined,
  max: 20,
  idleTimeoutMillis: 30000,
  connectionTimeoutMillis: 10000,
};

export const pool = new Pool(poolConfig);

pool.on('error', (err) => {
  console.error('❌ [DB Error] Unexpected PostgreSQL pool error:', err);
});

// Helper for running single queries
export const query = async (text: string, params?: any[]) => {
  const start = Date.now();
  try {
    const res = await pool.query(text, params);
    const duration = Date.now() - start;
    if (process.env.NODE_ENV === 'development' && duration > 100) {
      console.log(`⏱️ [DB Query] executed in ${duration}ms: ${text.slice(0, 80)}...`);
    }
    return res;
  } catch (error) {
    console.error(`❌ [DB Query Error] for query: ${text.slice(0, 100)}`, error);
    throw error;
  }
};

// Auto-seed demo user and initialize auxiliary tables if they don't exist yet
export const initDb = async () => {
  try {
    const client = await pool.connect();
    try {
      // 1. Auxiliary table for recommendation caching
      await client.query(`
        CREATE TABLE IF NOT EXISTS goal_recommendations (
          id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
          goal_id UUID REFERENCES goals(id) ON DELETE CASCADE,
          course_id UUID REFERENCES courses(id) ON DELETE CASCADE,
          rank INT NOT NULL,
          match_percentage NUMERIC(5, 2),
          score_breakdown JSONB,
          created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
        );
        CREATE INDEX IF NOT EXISTS idx_goal_recommendations_goal ON goal_recommendations(goal_id);
      `);

      // 2. Auto-seed Demo User (Alex Rivera with password123)
      // Hash generated by bcryptjs with 10 salt rounds.
      const demoHash = '$2b$10$vjD2aapnG7QJ8LeX2kplqekqGFKgRP7fu.DV43wJ0yPoTt16dyeSG';
      await client.query(`
        INSERT INTO users (id, email, password_hash, full_name, role, target_role, experience_level, bio)
        VALUES (
          'a0000000-0000-0000-0000-000000000001',
          'alex.rivera@pathfinder.ai',
          $1,
          'Alex Rivera',
          'student',
          'AI Solutions Architect',
          'intermediate',
          'Full-stack software engineer specializing in LLMs, high-scale RAG, and autonomous agent ecosystems.'
        )
        ON CONFLICT (email) DO UPDATE SET
          password_hash = EXCLUDED.password_hash,
          full_name = EXCLUDED.full_name,
          role = EXCLUDED.role,
          target_role = EXCLUDED.target_role,
          experience_level = EXCLUDED.experience_level,
          bio = EXCLUDED.bio,
          updated_at = CURRENT_TIMESTAMP;
      `, [demoHash]);

      // 3. Auto-seed Demo User Goal
      await client.query(`
        INSERT INTO goals (id, user_id, target_role, target_timeline_months, weekly_study_hours, preferred_learning_style, status, notes)
        VALUES (
          'c0000000-0000-0000-0000-000000000001',
          'a0000000-0000-0000-0000-000000000001',
          'Senior AI Solutions Architect',
          6,
          15,
          'hands_on_projects',
          'active',
          'Goal is to master distributed LLM serving, vector search at scale, and multi-agent coordination.'
        )
        ON CONFLICT (id) DO UPDATE SET
          user_id = EXCLUDED.user_id,
          target_role = EXCLUDED.target_role,
          target_timeline_months = EXCLUDED.target_timeline_months;
      `);

      // 4. Auto-seed Demo User Skills
      await client.query(`
        INSERT INTO user_skills (user_id, skill_id, proficiency_level, verified) VALUES
        ('a0000000-0000-0000-0000-000000000001', '10000000-0000-0000-0000-000000000001', 4, true),
        ('a0000000-0000-0000-0000-000000000001', '10000000-0000-0000-0000-000000000005', 3, true),
        ('a0000000-0000-0000-0000-000000000001', '10000000-0000-0000-0000-000000000007', 3, true),
        ('a0000000-0000-0000-0000-000000000001', '10000000-0000-0000-0000-000000000009', 2, false),
        ('a0000000-0000-0000-0000-000000000001', '10000000-0000-0000-0000-000000000010', 2, false),
        ('a0000000-0000-0000-0000-000000000001', '10000000-0000-0000-0000-000000000011', 1, false),
        ('a0000000-0000-0000-0000-000000000001', '10000000-0000-0000-0000-000000000012', 1, false)
        ON CONFLICT (user_id, skill_id) DO UPDATE SET
          proficiency_level = EXCLUDED.proficiency_level,
          verified = EXCLUDED.verified;
      `);

      console.log('✅ [DB] PostgreSQL connected & verified demo user (alex.rivera@pathfinder.ai / password123).');
    } finally {
      client.release();
    }
  } catch (err) {
    console.warn('⚠️ [DB] Warning initializing database/demo user:', err);
  }
};
